<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>jekyll</string>
    </array>
    <key>foldingStartMarker</key>
    <string>(?x){%\s*(if|unless|for|paginate|capture|form|case|tablerow|raw|comment)[^(%})]+%}</string>
    <key>foldingStopMarker</key>
    <string>(?x){%\s*(endif|endunless|endfor|endpaginate|endcapture|endform|endcase|endtablerow|endraw|endcomment)[^(%})]+%}</string>
    <key>name</key>
    <string>HTML (Jekyll)</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#front-matter</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>{%\s*comment\s*%}</string>
            <key>end</key>
            <string>{%\s*endcomment\s*%}</string>
            <key>name</key>
            <string>comment.block.jekyll</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>{{</string>
            <key>end</key>
            <string>}}</string>
            <key>name</key>
            <string>punctuation.output.jekyll</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#template_var</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>{%</string>
            <key>end</key>
            <string>%}</string>
            <key>name</key>
            <string>punctuation.tag.jekyll</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#template_tag_name</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#template_var</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.entry.jekyll</string>
                </dict>
                <key>10</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.jekyll</string>
                </dict>
                <key>11</key>
                <dict>
                    <key>name</key>
                    <string>string.unquoted.jekyll</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.jekyll</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.separator.key-value.jekyll</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.entry.jekyll</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>string.quoted.double.jekyll</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.jekyll</string>
                </dict>
                <key>7</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.jekyll</string>
                </dict>
                <key>8</key>
                <dict>
                    <key>name</key>
                    <string>string.quoted.single.jekyll</string>
                </dict>
                <key>9</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.jekyll</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(?:(?:(-\s*)?(\w+\s*(:)))|(-))\s*(?:((")[^"]*("))|((')[^']*('))|([^,{}&amp;#\[\]]+))\s*</string>
            <key>name</key>
            <string>string.unquoted.jekyll</string>
        </dict>
        <dict>
            <key>include</key>
            <string>text.html.basic</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>assign_op</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>/=</string>
                    <key>name</key>
                    <string>keyword.operator.assignment.augmented.jekyll</string>
                </dict>
            </array>
        </dict>
        <key>front-matter</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.entry.yaml.jekyll</string>
                        </dict>
                        <key>10</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.yaml.jekyll</string>
                        </dict>
                        <key>11</key>
                        <dict>
                            <key>name</key>
                            <string>string.unquoted.yaml.jekyll</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.yaml.jekyll</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.separator.key-value.yaml.jekyll</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.entry.yaml.jekyll</string>
                        </dict>
                        <key>5</key>
                        <dict>
                            <key>name</key>
                            <string>string.quoted.double.yaml.jekyll</string>
                        </dict>
                        <key>6</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.yaml.jekyll</string>
                        </dict>
                        <key>7</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.yaml.jekyll</string>
                        </dict>
                        <key>8</key>
                        <dict>
                            <key>name</key>
                            <string>string.quoted.single.yaml.jekyll</string>
                        </dict>
                        <key>9</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.yaml.jekyll</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?:(?:(-\s*)?(\w+\s*(:)))|(-))\s*(?:((")[^"]*("))|((')[^']*('))|([^,{}&amp;#\[\]]+))\s*</string>
                    <key>name</key>
                    <string>string.unquoted.yaml.jekyll</string>
                </dict>
            </array>
        </dict>
        <key>logic_expression</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>/=</string>
                    <key>name</key>
                    <string>keyword.operator.assignment.augmented.jekyll</string>
                </dict>
            </array>
        </dict>
        <key>logic_op</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\s+(and|or|not|contains|(\!\=|\=\=|&lt;\=|&gt;\=|&lt;|&gt;)\s+</string>
                    <key>name</key>
                    <string>keyword.operator.logical.jekyll</string>
                </dict>
            </array>
        </dict>
        <key>template_tag_name</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>(?&lt;={%)\s*(\w+)</string>
                    <key>name</key>
                    <string>entity.name.tag.jekyll</string>
                </dict>
            </array>
        </dict>
        <key>template_var</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>invalid.illegal.filter.jekyll</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>invalid.illegal.filter.jekyll</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(\[)(\|)(?=[^\]]*)(?=\])</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(?&lt;=\s)(\+|\-|\/|\*)(?=\s)</string>
                    <key>name</key>
                    <string>invalid.illegal.filter.jekyll</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(false|true|nil)</string>
                    <key>name</key>
                    <string>constant.language.jekyll</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>invalid.illegal.operator.jekyll</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?=if|unless|elsif)\s*[^%}]+\s(in)\s</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\s+(and|or|not|contains|in|by|((\!|\=|\&lt;|\&gt;)\=))\s+</string>
                    <key>name</key>
                    <string>keyword.operator.jekyll</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>invalid.illegal.assignment.jekyll</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?&lt;=assign)([^\=]+)(\=\=+)</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\|\s+(?![\.0-9])[a-zA-Z0-9_-]+\:\s+</string>
                    <key>name</key>
                    <string>support.function.with-args.jekyll</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\|\s+(?![\.0-9])[a-zA-Z0-9_-]+\s+</string>
                    <key>name</key>
                    <string>support.function.without-args.jekyll</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(?&lt;=\s)(with|offset\:|limit\:)(?=\s)</string>
                    <key>name</key>
                    <string>keyword.control.jekyll</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>invalid.illegal.argument.jekyll</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?&lt;=include)(.*)(with\:|offset|limit)(?=\s)</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(?&lt;=\s)(\w+\:)(?=\:\s)</string>
                    <key>name</key>
                    <string>invalid.illegal.jekyll</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>"</string>
                    <key>end</key>
                    <string>"</string>
                    <key>name</key>
                    <string>string.quoted.double.jekyll</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>'</string>
                    <key>end</key>
                    <string>'</string>
                    <key>name</key>
                    <string>string.quoted.single.jekyll</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(-|\+)?\s*[0-9]+(\.[0-9]+)?</string>
                    <key>name</key>
                    <string>constant.numeric.jekyll</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(collection|product|linklist|linklists|order|link|customer|customer_address|line_item|shop|collections|page_title|template|image|blog|blogs|cart|pages|theme|themes|variant|items|comment|forloop|settings)\b</string>
                    <key>name</key>
                    <string>support.class.jekyll</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(assets|author|body|body_raw|current|date|excerpt_raw|meta|next|pages|parent|posts|previous|site|tags|taxonomy|title|url)\b</string>
                    <key>name</key>
                    <string>support.class.jekyll</string>
                </dict>
                <dict>
                    <key>comment</key>
                    <string>global variables</string>
                    <key>match</key>
                    <string>\b(site|page|content|paginator)\b</string>
                    <key>name</key>
                    <string>support.class.jekyll</string>
                </dict>
                <dict>
                    <key>comment</key>
                    <string>page variables</string>
                    <key>match</key>
                    <string>\b(page\.(content|title|excerpt|url|date|id|categories|tags|path))\b</string>
                    <key>name</key>
                    <string>support.class.jekyll</string>
                </dict>
                <dict>
                    <key>comment</key>
                    <string>site variables</string>
                    <key>match</key>
                    <string>\b(site\.(time|p(ages|osts)|related_posts|categories|tags))\b</string>
                    <key>name</key>
                    <string>support.class.jekyll</string>
                </dict>
                <dict>
                    <key>comment</key>
                    <string>paginator variables</string>
                    <key>match</key>
                    <string>\b(per_page|posts|total_posts|page|previous_page|previous_page_path|next_page|next_page_path)\b</string>
                    <key>name</key>
                    <string>support.class.jekyll</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>((?&lt;=\w\:\s)\w+)</string>
                    <key>name</key>
                    <string>variable.parameter.jekyll</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(?&lt;=\.)\w+\b</string>
                    <key>name</key>
                    <string>support.variable.jekyll</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\w+</string>
                    <key>name</key>
                    <string>variable.other.jekyll</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>text.html.jekyll</string>
    <key>uuid</key>
    <string>02EE2FE6-91CB-4C5C-9A1C-A68777D6218E</string>
</dict>
</plist>
