<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>foldingStartMarker</key>
    <string>(?x)
        (&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)\b.*?&gt;
        |&lt;!--(?!.*--&gt;)
        |\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
        |{% highlight %}</string>
    <key>foldingStopMarker</key>
    <string>(?x)
        (&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)&gt;
        |^\s*--&gt;
        |(^|\s)\}
        |{% endhighlight %})</string>
    <key>keyEquivalent</key>
    <string>^~M</string>
    <key>name</key>
    <string>Markdown (Jekyll)</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#front-matter</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>{%\s*highlight(.*)%}</string>
            <key>end</key>
            <string>{%\s*endhighlight\s*%}</string>
            <key>name</key>
            <string>markup.heading.markdown.jekyll</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#codeblock</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>```.*</string>
            <key>end</key>
            <string>```</string>
            <key>name</key>
            <string>markup.heading.markdown.jekyll</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#codeblock</string>
                </dict>
            </array>
        </dict>
        <dict/>
        <dict>
            <key>include</key>
            <string>#link-footnote</string>
        </dict>
        <dict>
            <key>include</key>
            <string>text.html.markdown</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>codeblock</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>.*</string>
                    <key>name</key>
                    <string>comment.block.markdown.jekyll</string>
                </dict>
            </array>
        </dict>
        <key>front-matter</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.entry.yaml.jekyll</string>
                        </dict>
                        <key>10</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.yaml.jekyll</string>
                        </dict>
                        <key>11</key>
                        <dict>
                            <key>name</key>
                            <string>string.unquoted.yaml.jekyll</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.yaml.jekyll</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.separator.key-value.yaml.jekyll</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.entry.yaml.jekyll</string>
                        </dict>
                        <key>5</key>
                        <dict>
                            <key>name</key>
                            <string>string.quoted.double.yaml.jekyll</string>
                        </dict>
                        <key>6</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.yaml.jekyll</string>
                        </dict>
                        <key>7</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.yaml.jekyll</string>
                        </dict>
                        <key>8</key>
                        <dict>
                            <key>name</key>
                            <string>string.quoted.single.yaml.jekyll</string>
                        </dict>
                        <key>9</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.yaml.jekyll</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?:(?:(-\s*)?(\w+\s*(:)))|(-))\s*(?:((")[^"]*("))|((')[^']*('))|([^,{}&amp;#\[\]]+))\s*</string>
                    <key>name</key>
                    <string>string.unquoted.yaml.jekyll</string>
                </dict>
            </array>
        </dict>
        <key>link-footnote</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.constant.begin.markdown.jekyll</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>constant.other.reference.link.markdown.jekyll</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.constant.end.markdown.jekyll</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>.?(\[)([^\]]*)(\])</string>
                    <key>name</key>
                    <string>constant.other.reference.link.markdown.jekyll</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>text.html.markdown.jekyll</string>
    <key>uuid</key>
    <string>F5E04BF4-69A9-45AE-9205-B3F3C2B00130</string>
</dict>
</plist>
