<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>textile</string>
    </array>
    <key>firstLineMatch</key>
    <string>textile</string>
    <key>keyEquivalent</key>
    <string>^~T</string>
    <key>name</key>
    <string>Textile (Jekyll)</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#front-matter</string>
        </dict>
        <dict>
            <key>include</key>
            <string>text.html.textile</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>front-matter</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.entry.yaml.jekyll</string>
                        </dict>
                        <key>10</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.yaml.jekyll</string>
                        </dict>
                        <key>11</key>
                        <dict>
                            <key>name</key>
                            <string>string.unquoted.yaml.jekyll</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.yaml.jekyll</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.separator.key-value.yaml.jekyll</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.entry.yaml.jekyll</string>
                        </dict>
                        <key>5</key>
                        <dict>
                            <key>name</key>
                            <string>string.quoted.double.yaml.jekyll</string>
                        </dict>
                        <key>6</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.yaml.jekyll</string>
                        </dict>
                        <key>7</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.yaml.jekyll</string>
                        </dict>
                        <key>8</key>
                        <dict>
                            <key>name</key>
                            <string>string.quoted.single.yaml.jekyll</string>
                        </dict>
                        <key>9</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.yaml.jekyll</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?:(?:(-\s*)?(\w+\s*(:)))|(-))\s*(?:((")[^"]*("))|((')[^']*('))|([^,{}&amp;#\[\]]+))\s*</string>
                    <key>name</key>
                    <string>string.unquoted.yaml.jekyll</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>text.html.textile.jekyll</string>
    <key>uuid</key>
    <string>5895c5fb-39cb-445e-b7d1-4e50a4aab6de</string>
</dict>
</plist>
